### ISSUE TITLE
parametry energa_my_meter: w pliku config.yaml

### ISSUE THREAD

**Issue by jj641** [thedeemling/hass-energa-my-meter#5]
proszę o pomoc w zakresie okreslenie parametrów energa_my_meter: w pliku config.yaml

1. Moje konto w Enerdze to Client type: Wytwórca, taryfa G12

2. Odczyt ze strony mojlicznik.energa-operator.pl

{"ppes":[{"id":"111","isActive":true,"meters":[{"countners":[{"measurement_date":"2024-11-11 00:00","meter_value":"4835.884","tariff":"1"},{"measurement_date":"2024-11-11 00:00","meter_value":"3167.888","tariff":"2"}],"first_date":null,"last_update_date":"Mon, 11 Nov 2024 00:00:00 GMT","meter_type":"A+","meter_type_url":"A%2B"},{"countners":[{"measurement_date":"2024-11-11 00:00","meter_value":"9926.628","tariff":"1"},{"measurement_date":"2024-11-11 00:00","meter_value":"3950.984","tariff":"2"}],"first_date":null,"last_update_date":"Mon, 11 Nov 2024 00:00:00 GMT","meter_type":"A-","meter_type_url":"A-"}],"name":"333","type":"Wytw\u00f3rca"}]}	

3. Przykładowy kod:

```yaml
energa_my_meter:
  - password: pass
    username: user
    # The meter number that the integration should monitor
    selected_meter: 333
    # The internal Energa ID for the meter. Can be seen in API calls when checking the past usage
    selected_meter_internal_id: 111
    # Select all zones that you would like to monitor. Please ensure they will be added exactly as 
    # returned by Energa (with colon, if added there)
    selected_zones:
      - 'tariff:1'
      - 'tariff:2'
    # What kind of statistic sensors you would like to create
    selected_modes:
      - A+
      - A-
    # Optional. You can also configure it in the integration options (GUI)
    # Interval in *minutes* which will be used to refresh data from the Energa website
    # By default 300 minutes
    scan_interval: 310
    # Optional. How many historical days should be loaded initially, by default 10
    number_of_days_to_load: 400
```
	
skutkuje komunikatem:

Ostrzeżenia konfiguracji
Invalid config for 'energa_my_meter' at configuration.yaml, line 84: 'selected_zones' is an invalid option for 'energa_my_meter', check: energa_my_meter->0->selected_zones
Invalid config for 'energa_my_meter' at configuration.yaml, line 88: 'selected_modes' is an invalid option for 'energa_my_meter', check: energa_my_meter->0->selected_modes
Invalid config for 'energa_my_meter' at configuration.yaml, line 96: 'number_of_days_to_load' is an invalid option for 'energa_my_meter', check: energa_my_meter->0->number_of_days_to_load

**Comment by thedeemling** [comment]
Cześć!

Dziękuję za skorzystanie z mojego komponentu.

Przepraszam też za to niedociągnięcie - dawno nie testowałem funkcjonalności ładowania ustawień z YAML i... nie działała prawidłowo po ostatnich poprawkach związanych z wieloma strefami i licznikami.

Przetestowałem i poprawiłem wsparcie dla ładowania konfiguracji z pliku YAML w ramach nowej wersji [2.1.1](https://github.com/thedeemling/hass-energa-my-meter/releases/tag/2.1.0). Będziesz musiał zaktualizować sobie komponent przy użyciu HACSa lub ręcznie, w katalogu `custom_components`.

Samą konfigurację możesz załadować w następujacy sposób:

```yaml
energa_my_meter:
  - password: TWOJE_HASLO (najlepiej zaladować poprzez !secret)
    username: TWOJ_LOGIN
    selected_meter: 12345 # Twój numer licznika
    selected_meter_internal_id: 09876 # Wewnętrzne ID używane przez Energę do pobierania statystyk. Daj znać, jeżeli nie wiesz, jak je znaleźć
   # Lista stref, DOKŁADNIE taka, jaką zwraca Energa. W moim przypadku to:
    selected_zones:
      - "Strefa całodobowa:"
    # Te typy trzeba załadować w taki sposób :)
    selected_modes:
      - ENERGY_CONSUMED
      - ENERGY_PRODUCED
    scan_interval: 310
    number_of_days_to_load: 5
```

Wybacz za niedociągnięcie, większość użytkowników korzysta z GUI i - niestety - trochę zaniedbałem YAMLa.
